opensafely-core/release-hatch

hatch/app.py, hatch/config.py, tests/conftest.py, tests/test_app.py
This based on the same scheme as job-server, passing a secret in
Authoriztion header.
This will be expanded later to also support a signed token in the
Authorization header
=> Add simple job-server style authentication

hatch/app.py, hatch/config.py, hatch/models.py, tests/conftest.py, tests/factories.py, tests/test_app.py, tests/test_models.py
I release there was a security issue where a valid token for one
workspace could be used to access any release from any workspace. To
fix, I moved the releases to be stored inside their workspace dir, and
use that as an access control.
In the process, I refactored the test machinery out into reusable
factories.
=> Add release file index and serving apis

hatch/api_client.py, hatch/app.py, hatch/models.py, tests/test_api_client.py, tests/test_app.py
This is the only API that is not a mirror of job-server's API, as it
does not post the file, just it's name, and the service uploads the
file.
=> Add final API, file upload.

hatch/app.py, hatch/schema.py, tests/test_app.py
We now rewrite the Location header for creating a release to point to
hatch rather than forwarding the job-server's Location header.
The intention is for hatch clients (osrelease and the SPA) to use the url as the
endpoint for uploading files.
To facilitate this we change the upload api url. Rather than passing the
name of the file as a path parameter, we include it in the request body.
=> Refactor release-api for consistant url

dev-token.py, hatch/app.py, hatch/signing.py, tests/test_app.py, tests/test_signing.py
We do not need them, we just need the signed user. Job-server will
validate that the user has the correct permissions.
=> Remove scopes from auth token.

dev-token.py, hatch/__init__.py, hatch/app.py, hatch/signing.py, tests/conftest.py, tests/test_app.py, tests/test_signing.py
This works better in a job-server setting, where there is no default
signer, it's per backend. Signer's are cheap to create, so we do it on
the fly.
Also, explicit is better than implicit
=> Remove the default signer, and make the key and salt explict

hatch/models.py, hatch/schema.py, tests/test_models.py, tests/test_schema.py
Exclude lots more files from current files listing:
- metadata/
- releases/
- .*
Also, ensure all paths are normalised to url path separators in release
requests and indexes, to avoid windows \ separators appearing in urls
(which works but is ugly)
=> Fix some issues from testing on real workspaces on windows

hatch/app.py, hatch/models.py, tests/test_app.py, tests/test_models.py
This uses the configured hostname for the service to generate absolute URLs for files when building an index response.
We configure the SPA with the URL for the index endpoint, with each file in that response containing its canonical API endpoint URL.  Currently this URL is relative to the host, which matches the response from job-server (an entirely sensible thing to have done!).
However, in a release-hatch driven API the SPA loads the index from the URL job-server has constructed, and then a user clicking on a file triggers a fetch to a relative URL, which uses the job-server hostname.  Since the index URL and file URL have an overlapping prefix (eg `/workspace/<name>/current`) it's tricky to let the SPA merge them without giving it some knowledge of how the URLs work, something we've …
=> Use Absolute File URLs

pyproject.toml
This mirrors the exclusion of direnv directories elsewhere in the config, and avoids direnv's python venv from being checked for coverage.
=> Omit Direnv from Coverage

.github/workflows/main.yml, .test.env, Dockerfile, docker-compose.yaml, entrypoints/dev.sh, entrypoints/prod.sh, justfile, requirements.dev.in
Using this opportunity to try out a new Dockerfile methodology.
The docker is a multistage build, with the following stages:
```
┌──────────────────┐            ┌──────────────────┐
│   base-python    ├────────────►     builder      │
└────────┬─────────┘            └──────────┬───────┘
│                                 │
│                                 │COPY FROM
│     ┌──────────────────┐        │
└─────►release-hatch-base◄────────┘
└────────┬─┬───────┘
│ │
│ │
┌──────────────────┐    │ │     ┌──────────────────┐
│release-hatch-prod◄────┘ └─────►release-hatch-dev │
└──────────────────┘            └──────────────────┘
```
* base-python: basic python-on-ubuntu set up
* builder: install/build requirements
* release-hatch-base: base image with all deps but no code
* release-hatch-prod: …
=> Add Dockerfile for deploying to non-TPP backends

dotenv-sample.env
API_SERVER is used for the CORS middleware, but the calling server's
hostname arrives without a trailing slash, so mismatches.
=> Don't use trailing slash for job-server location

hatch/app.py, hatch/signing.py, tests/test_app.py, tests/test_signing.py
Previous we used the implicit hostname, now we explicitly use the
configure SERVER_HOST. This means we work when being accessed via nginx.
Also added some debug logging to validation errors, for future us.
=> Use the explit public url for validation

.github/workflows/main.yml, docker/Dockerfile, docker/docker-compose.yaml, docker/justfile, justfile
The main change is that we hardcode a prod uid/gid. This allows us to
use bind mounting directories in prod
Also clean up some of the docker justfile commands
* rename `docker-run` to `docker-serve`
* add `docker-run ...` as a wrapper round invoking `docker run ...`
* add `docker-exec ...` as a wrapper round invoking `docker exec ...`
Also clean up the naming of images in docker-compose to drop the
unnecessary and brittle `-prod` suffix for the prod image.
=> Refactor some docker based on prod set up

DEVELOPERS.md, README.md, dev-token.py, dotenv-sample.env, hatch/api_client.py, hatch/app.py, hatch/config.py, tests/conftest.py, tests/test_api_client.py, tests/test_app.py, tests/test_models.py
This allows them to share the same env file in prod.
Also, changed SERVER_HOST to RELEASE_HOST, so it was more obvious
=> Rename environment variables to match job-runner

hatch/app.py, hatch/config.py
Using JOBSERVER_API_ENDPOINT was a bug, as it includes the path
`/api/v2`, which breaks CORS preflight checks, as it's not an exact
match to the `Origin:` header send by browser.
Instead, we add explicit config, with a production default of
https://jobs.opensafely.org. This allows local override in dev, but the
default value works in prod.
=> Add new explicit SPA_ORIGIN config and use for CORS

docker/Dockerfile, docker/justfile
The volume mounts were originally added as metadata, but it turns out if you don't supply a mount, docker creates one for you with the contents of that dir in your that lasts beyond the containers lifetime and eats disk.
=> fix: remove docker volumes

hatch/app.py, hatch/signing.py, tests/test_app.py, tests/test_signing.py
Previously, release-hatch validated that the full url we were handling
matched the token url prefix.
This meant we could only support one valid host. This has proved
problematic, as this included the port. For various reasons, EMIS users
access via one port when viewing outputs (because SSH forwarding)
and another when releasing outputs via `osrelease`. Also, localhost is
common access for testing and other operations, so it would be nice to
support that as an option.
This PR decouples the url validation into a hostname check (w/o ports),
and a path check.
It also tightens up the validation of urls in the signed token, so a url
must be valid.
=> fix: decouple validating hostname from path.

hatch/app.py, hatch/models.py, hatch/schema.py, requirements.dev.txt, tests/test_api_client.py, tests/test_app.py, tests/test_models.py
This modifies the release creation API to support an alternate payload
POSTed from the SPA, rather than the current minimal osrelease payload.
This alternate payload is the same json format as the data we sent to
the SPA, so should be easy to reflect back. It includes an extra field,
`metadata`, to be populated by the SPA. We also remove the `user` field
as it was not used.
This consolidates the json schema to a single playload type, the
FileList, which is used for both listing files and requesting files for
review, which is much simpler. As such, it has been renamed to be
reflect its more general purpose.
There are few places where we have to branch to handle the appropriate
payload. Once the release UI in SPA is fully launched, we should be able
to delete the osrelease method.
=> Add support to request a release via the SPA.

hatch/schema.py, tests/test_api_client.py, tests/test_app.py, tests/test_models.py
This provides a place to put whole-release level fields that users may
need to fill in. We just pass it through to job-server.
=> Add release level metadata to the review API

hatch/app.py, hatch/client.py, justfile, requirements.prod.txt, tests/test_client.py
Refactor cli arguments and clean it up a bit in preparation for adding
a new command
Also, remove the time.sleep() calls in the functional tests with some
trickery. Saves about 6-8s of the test run times on my machine.
=> cli tool refactor

hatch/app.py, hatch/client.py, hatch/models.py, hatch/schema.py, tests/test_api_client.py, tests/test_app.py, tests/test_models.py
We are moving osrelease to use the new API, so we do not need to support
both simultaneously.
=> Remove old release API support
